# Generated by Django 6.0.2 on 2026-02-21 20:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('total_sales_count', models.PositiveIntegerField(default=0)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Umar Homes', max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('landowner_name', models.CharField(max_length=255)),
                ('total_plots', models.PositiveIntegerField()),
                ('plot_sizes', models.CharField(help_text='e.g., 5 Marla, 10 Marla, 1 Kanal', max_length=255)),
                ('landowner_commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Commission % from landowner', max_digits=5)),
                ('down_payment_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Down payment % requirement', max_digits=5)),
                ('payment_plan_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot_number', models.CharField(max_length=50)),
                ('plot_size', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_plots', to='customers.customer')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_plots', to='real_estate.dealer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='real_estate.project')),
            ],
            options={
                'ordering': ['plot_number'],
                'unique_together': {('project', 'plot_number')},
            },
        ),
    ]
