# Generated by Django 6.0.2 on 2026-02-21 20:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments_count', models.PositiveIntegerField(default=0)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('landowner_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('dealer_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_purchases', to='customers.customer')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_sales', to='real_estate.dealer')),
                ('plot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_record', to='real_estate.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='real_estate.realestatesale')),
            ],
        ),
    ]
