# Generated by Django 6.0.2 on 2026-02-21 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_realestatesale_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='commission_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='dealer_commission_type',
            field=models.CharField(choices=[('PLOT_PRICE', '% of Total Plot Price'), ('COMPANY_COMMISSION', '% of Company (Landowner) Commission')], default='PLOT_PRICE', help_text='Basis for dealer commission calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='dealer_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid to the dealer for this sale', max_digits=12),
        ),
    ]
