# Generated by Django 6.0.2 on 2026-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_realestatesale_commission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_type',
            field=models.CharField(choices=[('TEAM_MEMBER', 'Team Member'), ('DEALER', 'Dealer'), ('SUB_AGENT', 'Sub-agent')], default='DEALER', max_length=20),
        ),
    ]
