# Generated by Django 6.0.2 on 2026-03-05 06:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_realestateexpense_realestateincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='landowner_commission_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission actually received from Landowner', max_digits=12),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='received_down_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual Down Payment Received at booking', max_digits=12),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='registration_number',
            field=models.CharField(blank=True, help_text='e.g., 1,001', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='realestatesale',
            name='dealer_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Commission for Dealer', max_digits=12),
        ),
        migrations.AlterField(
            model_name='realestatesale',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, help_text='Required Down Payment (e.g. 30%)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='realestatesale',
            name='landowner_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Commission from Landowner', max_digits=12),
        ),
    ]
