# Generated by Django 6.0.2 on 2026-03-12 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_realestatesale_landowner_commission_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='landowner_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid to the landowner for this sale', max_digits=12),
        ),
        migrations.AlterField(
            model_name='realestateexpense',
            name='category',
            field=models.CharField(choices=[('OFFICE_RENT', 'Office Rent'), ('SALARY', 'Salary'), ('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('COMMISSION_PAID', 'Commission Paid'), ('MISC', 'Misc Expenses')], max_length=50),
        ),
    ]
