# Generated by Django 6.0.2 on 2026-03-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_realestatesale_landowner_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='realestateincome',
            name='income_type',
            field=models.CharField(choices=[('COMMISSION_RECEIVED', 'Commission Received'), ('INSTALLMENT_PAYMENT', 'Installment Payment'), ('OTHER', 'Other Income')], max_length=50),
        ),
    ]
