# Generated by Django 6.0.2 on 2026-03-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_installment_paid_amount_alter_installment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='landowner_payment_remarks',
            field=models.TextField(blank=True, help_text='Remarks for the last payment made to landowner', null=True),
        ),
        migrations.AlterField(
            model_name='realestateexpense',
            name='category',
            field=models.CharField(choices=[('OFFICE_RENT', 'Office Rent'), ('SALARY', 'Salary'), ('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('COMMISSION_PAID', 'Commission Paid'), ('LANDOWNER_PAYOUT', 'Landowner Payout'), ('MISC', 'Misc Expenses')], max_length=50),
        ),
    ]
