# Generated by Django 6.0.2 on 2026-03-13 09:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_realestatesale_landowner_payment_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='payment_remarks',
            field=models.CharField(blank=True, help_text="Temporary field for last payment's remarks", max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='real_estate.installment')),
            ],
            options={
                'ordering': ['payment_date', 'created_at'],
            },
        ),
    ]
