# Generated by Django 6.0.2 on 2026-03-14 06:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_installment_payment_remarks_installmentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='semi_annual_balloon_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be paid every 6 months as a lump sum', max_digits=12),
        ),
    ]
