# Generated by Django 6.0.2 on 2026-03-14 20:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_realestatesale_semi_annual_balloon_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='allocation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='block_name',
            field=models.CharField(blank=True, help_text='e.g., Sector A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='confirmation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='cutting_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='e.g., 10%', max_digits=5),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='last_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='realestatesale',
            name='possession_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
