# Generated by Django 6.0.2 on 2026-03-14 23:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_dealerpayment_landownerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandownerCommissionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landowner_commission_history', to='real_estate.realestatesale')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
