# Generated by Django 6.0.2 on 2026-03-15 14:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0014_landownercommissionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='processing_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
