# Generated by Django 6.0.2 on 2026-04-07 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0015_realestatesale_processing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Temporary field for manual receipt record', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='realestatesale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
