# Generated by Django 6.0.2 on 2026-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0016_installment_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Manual receipt number for booking/down-payment', max_length=100, null=True),
        ),
    ]
