# Generated by Django 6.0.2 on 2026-04-07 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0017_realestatesale_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateexpense',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_expenses', to='real_estate.realestatesale'),
        ),
    ]
