# Generated by Django 6.0.2 on 2026-04-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0018_realestateexpense_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateincome',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_entries', to='real_estate.realestatesale'),
        ),
    ]
