# Generated by Django 6.0.2 on 2026-04-23 20:45

import django.db.models.deletion
import real_estate.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0019_realestateincome_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerpayment',
            name='date',
            field=models.DateField(default=real_estate.models._today),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='payment_date',
            field=models.DateField(default=real_estate.models._today),
        ),
        migrations.AlterField(
            model_name='landownercommissionpayment',
            name='date',
            field=models.DateField(default=real_estate.models._today),
        ),
        migrations.AlterField(
            model_name='landownerpayment',
            name='date',
            field=models.DateField(default=real_estate.models._today),
        ),
        migrations.AlterField(
            model_name='realestateexpense',
            name='date',
            field=models.DateField(default=real_estate.models._today),
        ),
        migrations.AlterField(
            model_name='realestateincome',
            name='date',
            field=models.DateField(default=real_estate.models._today),
        ),
        migrations.AlterField(
            model_name='realestateincome',
            name='income_type',
            field=models.CharField(choices=[('COMMISSION_RECEIVED', 'Commission Received'), ('INSTALLMENT_PAYMENT', 'Installment Payment'), ('DOWN_PAYMENT', 'Down Payment'), ('OTHER', 'Other Income')], max_length=50),
        ),
        migrations.AlterField(
            model_name='realestatesale',
            name='sale_date',
            field=models.DateField(default=real_estate.models._today),
        ),
        migrations.CreateModel(
            name='DownPaymentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=real_estate.models._today)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='down_payment_history', to='real_estate.realestatesale')),
            ],
            options={
                'ordering': ['payment_date', 'created_at'],
            },
        ),
    ]
