# Generated by Django 6.0.2 on 2026-04-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0020_alter_dealerpayment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatesale',
            name='remarks',
            field=models.TextField(blank=True, help_text='General remarks or initial down payment remarks', null=True),
        ),
    ]
