# Generated by Django 6.0.2 on 2026-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0022_ensure_downpaymentpayment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateexpense',
            name='source_payment_id',
            field=models.UUIDField(blank=True, help_text='ID of the specific payment record that created this expense', null=True),
        ),
        migrations.AddField(
            model_name='realestateincome',
            name='source_payment_id',
            field=models.UUIDField(blank=True, help_text='ID of the specific payment record that created this income', null=True),
        ),
    ]
