# Generated by Django 6.0.2 on 2026-03-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SALES_AGENT', 'Sales Agent'), ('ACCOUNTANT', 'Accountant')], default='ADMIN', max_length=20),
        ),
    ]
