# Generated by Django 6.0.2 on 2026-02-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='cnic',
            field=models.CharField(blank=True, help_text="Customer's CNIC number", max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='father_name',
            field=models.CharField(blank=True, help_text="Customer's father's name", max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="Customer's WhatsApp number", max_length=20),
        ),
    ]
