# Generated by Django 6.0.2 on 2026-02-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, help_text='Company or business name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Tax identification number', max_length=50, null=True),
        ),
    ]
